### PR TITLE
Fix X509 Certificate reading error

### PR DESCRIPTION
**Pull request by duane-talentsonar**
When the X509 certificate was read an extra `undefined` was appended to the data.

The last `.replace()` was missing the substitution string parameter, which was defaulted to `undefined`.

### CODE REVIEW

**Comment by duane-talentsonar** [comment]
PTAL

**Comment by akeating** [comment]
LGTM

**Comment by mhfrantz** [comment]
Are we going to upstream this?

**Comment by duane-talentsonar** [comment]
Yes, I am. Unfortunately, I'm out of step with the PRs. I submitted a PR from a different fork. I'll get it back in sync.

**Pull request merged**
